In [325]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [326]:
df = pd.read_csv('dataset/place.csv')
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [327]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB


In [328]:
df.describe()

cgpa     package
count  200.000000  200.000000
mean     6.990500    2.996050
std      1.069409    0.691644
min      4.260000    1.370000
25%      6.190000    2.487500
50%      6.965000    2.995000
75%      7.737500    3.492500
max      9.580000    4.620000

In [329]:
df.isnull().sum()

cgpa       0
package    0
dtype: int64

In [330]:
x = pd.DataFrame(df.iloc[:,0])
x

cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [331]:
y = pd.DataFrame(df.iloc[:,1])
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [332]:
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=2)

In [333]:
x_train

cgpa
137  7.14
163  8.93
111  5.42
123  5.10
109  7.77
..    ...
43   7.66
22   6.14
72   7.78
15   7.25
168  8.65

[160 rows x 1 columns]

In [334]:
x_test

cgpa
112  8.58
29   7.15
182  5.88
199  6.22
193  4.57
85   4.79
10   5.32
54   6.86
115  8.35
35   6.87
12   8.94
92   7.90
13   6.93
126  5.91
174  7.32
2    7.82
44   5.09
3    7.42
113  6.94
14   7.73
23   6.19
25   7.28
6    6.73
134  7.20
165  8.21
173  6.75
45   7.87
65   7.60
48   8.63
122  5.12
178  8.15
64   7.36
9    8.31
57   6.60
78   6.59
71   7.47
128  7.93
176  6.29
131  6.37
53   6.47

In [335]:
y_train

package
137     3.13
163     3.91
111     2.25
123     2.30
109     4.06
..       ...
43      2.76
22      2.30
72      3.62
15      3.23
168     3.52

[160 rows x 1 columns]

In [336]:
y_test

package
112     4.10
29      3.49
182     2.08
199     2.33
193     1.94
85      1.48
10      1.86
54      3.09
115     4.21
35      2.87
12      3.65
92      4.00
13      2.89
126     2.60
174     2.99
2       3.25
44      1.86
3       3.67
113     2.37
14      3.42
23      2.48
25      3.65
6       2.60
134     2.83
165     4.08
173     2.56
45      3.58
65      3.81
48      4.09
122     2.01
178     3.63
64      2.92
9       3.51
57      1.94
78      2.21
71      3.34
128     3.34
176     3.23
131     2.01
53      2.61

**LinearRegression**

In [337]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [338]:
y_pred = lr.predict(x_test)
y_pred

array([[3.89111601],
       [3.09324469],
       [2.38464568],
       [2.57434935],
       [1.6537286 ],
       [1.77647803],
       [2.07219258],
       [2.93143862],
       [3.76278706],
       [2.93701814],
       [4.09197872],
       [3.51170867],
       [2.97049525],
       [2.40138424],
       [3.18809652],
       [3.46707251],
       [1.94386362],
       [3.24389172],
       [2.97607477],
       [3.41685683],
       [2.55761079],
       [3.16577844],
       [2.85890486],
       [3.12114229],
       [3.68467378],
       [2.8700639 ],
       [3.49497011],
       [3.34432308],
       [3.91901361],
       [1.96060218],
       [3.65119666],
       [3.2104146 ],
       [3.74046898],
       [2.7863711 ],
       [2.78079158],
       [3.27178932],
       [3.52844723],
       [2.61340599],
       [2.65804215],
       [2.71383735]])

In [339]:
r2_LR = r2_score(y_test , y_pred)
r2_LR

0.780730147510384

In [340]:
mse_LR = mean_squared_error(y_test ,y_pred)
mse_LR

0.12129235313495527

In [341]:
mae_LR = mean_absolute_error(y_test ,y_pred)
mae_LR

0.2884710931878175

In [342]:
rmse_LR = np.sqrt(mse_LR)
rmse_LR

0.34827051717731616

**RandomForestRegression**

In [343]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators=100 , random_state=0)
rfr.fit(x_train , y_train)

C:\Users\CS-L2-PC09\AppData\Local\Temp\ipykernel_10824\972859175.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(x_train , y_train)


RandomForestRegressor(random_state=0)

In [344]:
y_pred1 = rfr.predict(x_test)
y_pred1

array([4.01535   , 3.07161667, 2.51544425, 2.51506667, 1.5274    ,
       1.5779    , 2.03739   , 3.09366833, 3.83196   , 3.149435  ,
       4.1343    , 3.50698333, 2.66027833, 2.46505   , 3.142615  ,
       3.5528    , 2.0616    , 3.2147    , 3.19908452, 3.6267    ,
       2.66471667, 3.11092095, 3.1583    , 2.67413333, 3.5338    ,
       2.7182    , 3.18115   , 3.1218    , 4.07775   , 1.8656    ,
       3.6863    , 3.1987    , 3.5429    , 2.89551333, 2.89441333,
       2.9792    , 3.87596667, 2.8196    , 2.5788    , 2.808     ])

In [345]:
r2_RFR = r2_score(y_test , y_pred1)
r2_RFR

0.7048919868621597

In [346]:
mse_RFR = mean_squared_error(y_test ,y_pred1)
mse_RFR

0.16324335031039014

In [347]:
mae_RFR = mean_absolute_error(y_test ,y_pred1)
mae_RFR

0.3357630287698414

In [348]:
rmse_RFR = np.sqrt(mse_RFR)
rmse_RFR

0.40403384797611963

**SupportVectorRegression**

In [349]:
from sklearn.svm import SVR
svr = SVR(kernel='rbf')
svr.fit(x_train,y_train)

C:\Users\CS-L2-PC09\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [350]:
y_pred2 = svr.predict(x_test)
y_pred2

array([3.9404953 , 3.08322305, 2.39316608, 2.61938084, 1.54776871,
       1.6045154 , 1.97998245, 2.9658129 , 3.85438947, 2.96988092,
       4.04207188, 3.5772923 , 2.99388329, 2.41339177, 3.16581861,
       3.51558963, 1.79559327, 3.2238153 , 2.99783728, 3.44527595,
       2.59974216, 3.14469917, 2.90999322, 3.10569945, 3.78465132,
       2.91900654, 3.55434677, 3.34632961, 3.95603378, 1.81889656,
       3.7499406 , 3.18811073, 3.83602282, 2.8467559 , 2.84154096,
       3.25563638, 3.5999126 , 2.66466013, 2.71506576, 2.77514689])

In [351]:
r2_SVR = r2_score(y_test , y_pred2)
r2_SVR

0.7719427993674634

In [352]:
mse_SVR = mean_squared_error(y_test ,y_pred2)
mse_SVR

0.12615320437359695

In [353]:
mae_SVR = mean_absolute_error(y_test ,y_pred2)
mae_SVR

0.2951826040245443

In [354]:
rmse_SVR = np.sqrt(mse_SVR)
rmse_SVR

0.3551805236405805

**LassoRegression**

In [355]:
from sklearn.linear_model import Lasso
la = Lasso(alpha=3.0)
la.fit(x_train , y_train)

Lasso(alpha=3.0)

In [356]:
y_pred3 = la.predict(x_test)
y_pred3

array([3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375,
       3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375,
       3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375,
       3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375,
       3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375,
       3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375, 3.0039375,
       3.0039375, 3.0039375, 3.0039375, 3.0039375])

In [357]:
r2_LA = r2_score(y_test , y_pred3)
r2_LA

-0.0028116694099722395

In [358]:
mse_LA = mean_squared_error(y_test ,y_pred3)
mse_LA

0.5547200664062499

In [359]:
mae_LA = mean_absolute_error(y_test ,y_pred3)
mae_LA

0.6426968750000001

In [360]:
rmse_LA = np.sqrt(mse_LA)
rmse_LA

0.7447953184642409

In [361]:
df1 = pd.DataFrame({'Regression_Name':['LinearRegression','RandomForestRegression','SupportVectorRegression','LassoRegression'] , 'r2_score':[r2_LR,r2_RFR,r2_SVR,r2_LA] , 'mse':[mse_LR,mse_RFR,mse_SVR,mse_LA] ,'mae':[mae_LR,mae_RFR,mae_SVR,mae_LA],'rmse':[rmse_LR,rmse_RFR,rmse_SVR,rmse_LA]})
df1

Regression_Name  r2_score       mse       mae      rmse
0         LinearRegression  0.780730  0.121292  0.288471  0.348271
1   RandomForestRegression  0.704892  0.163243  0.335763  0.404034
2  SupportVectorRegression  0.771943  0.126153  0.295183  0.355181
3          LassoRegression -0.002812  0.554720  0.642697  0.744795