# NUMPY LIBRARY

In [3]:
import numpy as np
np.__version__
'1.21.5'

'1.21.5'

# CREATE A 1-D ARRAY USING array()

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# Create A 1-D ARRAY USING arange()

In [5]:
import numpy as np
a=np.arange(3)
print(a)
print(a.dtype)
print(a.shape)

[0 1 2]
int32
(3,)


# CREATE A 2-D ARRAY USING array()

In [6]:
import numpy as np
b=np.array(([1,2,3],[4,5,6]))
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# CREATE A 2-D ARRAY USING arange()

In [7]:
import numpy as np
b=np.arange(10).reshape(2,5)
print(b)
print(b.dtype)
print(b.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
(2, 5)


In [8]:
import numpy as np
b=np.arange(10).reshape(5,2)
print(b)
print(b.dtype)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# CREATE A 3-D ARRAY USING array()

In [9]:
import numpy as np
c=np.array(
    [
    [[1,2,3],[5,6,7]],
    [[8,9,10],[11,12,13]],
    [[14,15,16],[17,18,19]]
    ]
)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING arange()

In [11]:
import numpy as np
c=np.arange(1,19).reshape(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
int32
(3, 3, 2)


# CREATE ARRAY OF ONES (1-D)

In [12]:
import numpy as np
d=np.ones(2,dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[1 1]
int32
(2,)


# CREATE ARRAY OF ONES(2-D)

In [13]:
import numpy as np
d=np.ones((2,3),dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# CREATE ARRAY OF ONES(2-D)

In [14]:
import numpy as np
d=np.ones((2,3),dtype=np.int32)
print(d)
print(d.dtype)
print(d.shape)

[[1 1 1]
 [1 1 1]]
int32
(2, 3)


# CREATE ARRAY OF ONES(3-D)

In [15]:
import numpy as np
d=np.ones((3,2,3),dtype="int32")
print(d)
print(d.dtype)
print(d.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32
(3, 2, 3)


# CREATE ARRAY OF ZEROS(1-D)

In [16]:
import numpy as np
f=np.zeros((3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[0 0 0]
int32
(3,)


# CREATE ARRAY OF ZEROS(2-D)

In [17]:
import numpy as np
f=np.zeros((2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[0 0 0]
 [0 0 0]]
int32
(2, 3)


# CREATE ARRAY OF ZEROS(3-D)

In [18]:
import numpy as np
f=np.zeros((3,2,3),dtype=np.int32)
print(f)
print(f.dtype)
print(f.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32
(3, 2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(1-D)

In [19]:
import numpy as np
a=np.random.randint(1,6,size=(6))
print(a)
print(a.dtype)
print(a.shape)

[4 5 3 4 1 3]
int32
(6,)


# CREATE AN ARRAY WITH RANDOM NUMBERS(2-D)

In [20]:
import numpy as np
b=np.random.randint(1,11,size=(2,3))
print(b)
print(b.dtype)
print(b.shape)

[[ 5  1 10]
 [ 9  1  5]]
int32
(2, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [22]:
import numpy as np
c=np.random.randint(10,21,size=(3,2,3))
print(c)
print(c.dtype)
print(c.shape)

[[[17 13 14]
  [20 18 12]]

 [[18 13 15]
  [14 17 12]]

 [[13 12 11]
  [11 14 20]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [1]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 6 15  7]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [2]:
import numpy as np
b=np.random.randint([1,2,3],10)
print(b)
print(b.dtype)
print(b.shape)

[7 2 3]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [3]:
import numpy as np
b=np.random.randint([1,2,3,5],[10,20,30,40])
print(a)
print(a.dtype)
print(a.shape)

[ 6 15  7]
int32
(3,)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (1-D)

In [4]:
import numpy as np
a=np.random.randn(5)
print(a)
print(a.dtype)
print(a.shape)

[-1.34370101 -0.69461888 -1.2626062  -0.1862085   0.63412293]
float64
(5,)


# CREATE NUMPY WITH RANDOM NUMBERS USING randn() (2-D)

In [5]:
import numpy as np
b=np.random.randn(3,2)
print(b)
print(b.dtype)
print(b.shape)

[[ 1.73353282  0.18180597]
 [ 1.19088703  0.25626748]
 [-0.50982979 -0.63276622]]
float64
(3, 2)


# CREATE ARRAY WITH RANDOM NUMBERS USING randn() (3-D)

In [6]:
import numpy as np
c=np.random.randn(3,3,2)
print(c)
print(c.dtype)
print(c.shape)

[[[-0.92177914  0.20779461]
  [-0.03172508  0.17811657]
  [ 1.45446568 -0.59501582]]

 [[-1.13273379 -0.9304511 ]
  [-0.79292336  0.50279463]
  [ 0.0586013  -1.34315876]]

 [[-1.85253832  0.9444219 ]
  [ 0.82008336  0.21302347]
  [-0.67949653 -1.17685757]]]
float64
(3, 3, 2)


# CREATE ARRAY OF RANDOM NUMBERS USING rand()

In [7]:
import numpy as np
a=np.random.rand(5)
print(a)
print(a.dtype)
print(a.shape)

[0.48280252 0.88288868 0.90930596 0.34457064 0.6396612 ]
float64
(5,)


# POSITIVE INDEXING IN ARRAY(left-right)

In [13]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2])
print(arr[7])
arr[3]

3
8


4

In [14]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arr[0,2])
print(arr[1,1])
print(arr[1,0])
print(arr[2,1])

3
6
5
9


In [15]:
#array with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[4,5,6]],
        [[10,20,30],[12,13,14]],
        [[100,200,300],[400,500,600]]    
    ]
            )
print(arr[0,1,1])
print(arr[2,1,0])
print(arr[1,1,1])

5
400
13


# NEGETIVE INDEXING IN ARRAY(right - left)

In [16]:
#array with 1-D
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-2])
print(arr[-1])
print(arr[-7])

6
7
1


In [17]:
#array with 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[-1,-2])
print(arr[-2,-1])

5
3


In [18]:
#arry with 3-D
import numpy as np
arr=np.array(
    [
        [[1,2,3],[5,6,7]],
        [[12,13,14],[11,10,49]]
    ]
            )
print(arr[-1,-1,-3])
print(arr[-2,-1,-3])

11
5


# MIXING OF (+ AND -)

In [19]:
import numpy as np
arr=np.array(
    [
        [[2,3,4],[5,6,7]],
        [[10,2,4],[6,7,29]],
        [[22,11,14],[23,45,44]]
    ]
)
print(arr[1,1,1])
print(arr[-2,-1,-2])
print(arr[2,-1,2])
print(arr[-1,1,-2])

7
7
44
45


# NUMPY ARRAY SLICING

In [20]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

# NEGETIVE SLICING

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])
print(arr[-6:-2])

[5 6]
[2 3 4 5]


In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# SLICING 2-D ARRAY

In [25]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [26]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [27]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

In [28]:
import numpy as np
arr = np.array([1,2,3,4,5])
a = arr.copy()
print("original array")
print(arr)
print("affected array")
arr[2] = 10
print(arr)
print(a)

original array
[1 2 3 4 5]
affected array
[ 1  2 10  4  5]
[1 2 3 4 5]


In [29]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
print("original array")
print(arr)
print("viewed array")
print(x)
print("affected array")
arr[0] = 30
print("arr : ",arr)
print(" x :",x)

original array
[1 2 3 4 5]
viewed array
[1 2 3 4 5]
affected array
arr :  [30  2  3  4  5]
 x : [30  2  3  4  5]


# Reshape Function()

In [1]:
#1d
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("original array :",arr) 

original array : [ 1  2  3  4  5  6  7  8  9 10]


In [2]:
#2D ARRAY
b = arr.reshape(5,2) 
print("2D array with shape 5x2")
print(b)
c = arr.reshape(2,5) 
print("2D array with shape 2x5")
print(c)

2D array with shape 5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2D array with shape 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
#3D ARRAY 
d = arr.reshape(2,1,5)
print("3D array with shape 2,1,5")
print(d)

3D array with shape 2,1,5
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# AGREEGATION FUNCTIONS
sum() FUNCTION

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5]) #1D
print("original 1D array : ",arr)
print(f"sum={np.sum(arr)}")
print()
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original 2D array : ",arr1)
print(f"sum={np.sum(arr1)}")
print()
arr2=np.array(
              [
               [[1,2,3],[4,5,6]],
               [[10,20,30],[40,50,60]]    
              ]
             )
print("original 3D array : ",arr2)
print(f"sum={np.sum(arr2)}")

original 1D array :  [1 2 3 4 5]
sum=15

original 2D array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
sum=55

original 3D array :  [[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]
sum=231


In [6]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n:",arr)
print("Across Colswise") #column wise
print("sum =",np.sum(arr , axis=0))
print("Across Rowswise") #Row wise
print("sum =",np.sum(arr , axis=1))

original array 
: [[1 2 3 4]
 [5 6 7 8]]
Across Colswise
sum = [ 6  8 10 12]
Across Rowswise
sum = [10 26]


In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n: ",arr)
print("Across Rows") #column wise
print("Mean =",np.mean(arr , axis=0))
print("Across Columns") #Row wise
print("Mean =",np.mean(arr , axis=1))

original array 
:  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
Mean = [3. 4. 5. 6.]
Across Columns
Mean = [2.5 6.5]


# std() FUNCTION

In [8]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array \n: ",arr)
print("Across Rows") #column wise
print("Mean =",np.mean(arr , axis=0))
print("Across Columns") #Row wise
print("Mean =",np.mean(arr , axis=1))


original array 
:  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
Mean = [3. 4. 5. 6.]
Across Columns
Mean = [2.5 6.5]


In [10]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print()
print("standard div :",np.std(arr))

original array : [[1 2 3 4]
 [5 6 7 8]]

standard div : 2.29128784747792


In [11]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("std div =",np.std(arr , axis=0))
print()
print("Across Columns") #Row wise
print("std div =",np.std(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
std div = [2. 2. 2. 2.]

Across Columns
std div = [1.11803399 1.11803399]


# Var() FUNCTION

In [12]:
# import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array :",arr)
print()
print("varients :",np.var(arr))

original array : [[1 2 3 4]
 [5 6 7 8]]

varients : 5.25


In [15]:
# import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array :,arr")
print("Across Rows")
print("var =",np.var(arr , axis=0))
print()
print("Across Columns")
print("var =",np.var(arr, axis=0))

original array :,arr
Across Rows
var = [4. 4. 4. 4.]

Across Columns
var = [4. 4. 4. 4.]


# Min() FUNCTION

In [16]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("minimum : ",np.min(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

minimum :  1


In [17]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("min =",np.min(arr , axis=0))
print()
print("Across Columns") #Row wise
print("min =",np.min(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
min = [1 2 3 4]

Across Columns
min = [1 5]


# Max() FUNCTION

In [18]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print()
print("maximum : ",np.max(arr)) 

original array :  [[1 2 3 4]
 [5 6 7 8]]

maximum :  8


In [20]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("original array : ",arr)
print("Across Rows") #column wise
print("max =",np.max(arr , axis=0))
print()
print("Across Columns") #Row wise
print("max =",np.max(arr , axis=1))

original array :  [[1 2 3 4]
 [5 6 7 8]]
Across Rows
max = [5 6 7 8]

Across Columns
max = [4 8]
