# Decision_Tree_Exercise

# For the Bank Marketing dataset available in UCI Machine Learning Repository, induct a decision tree to predict whether a client will subscribe to a term deposit or not (given in column 'y'). 

# 1.. Consider the column 'y' as the target variable. From the remaining columns, consider all except 'duration' as predictors

In [3]:
import numpy as np
import pandas as pd

In [4]:
a=pd.read_csv("bankadditionalfull1603958996760.zip")
a

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [5]:
a['job'].unique()

array(['housemaid', 'services', 'admin.', 'blue-collar', 'technician',
       'retired', 'management', 'unemployed', 'self-employed', 'unknown',
       'entrepreneur', 'student'], dtype=object)

In [6]:
a.describe()

age      duration      campaign         pdays      previous  \
count  41188.00000  41188.000000  41188.000000  41188.000000  41188.000000   
mean      40.02406    258.285010      2.567593    962.475454      0.172963   
std       10.42125    259.279249      2.770014    186.910907      0.494901   
min       17.00000      0.000000      1.000000      0.000000      0.000000   
25%       32.00000    102.000000      1.000000    999.000000      0.000000   
50%       38.00000    180.000000      2.000000    999.000000      0.000000   
75%       47.00000    319.000000      3.000000    999.000000      0.000000   
max       98.00000   4918.000000     56.000000    999.000000      7.000000   

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed  
count  41188.000000    41188.000000   41188.000000  41188.000000  41188.000000  
mean       0.081886       93.575664     -40.502600      3.621291   5167.035911  
std        1.570960        0.578840       4.628198      1.734447     72.251528  
min       -3.400000       92.201000     -50.800000      0.634000   4963.600000  
25%       -1.800000       93.075000     -42.700000      1.344000   5099.100000  
50%        1.100000       93.749000     -41.800000      4.857000   5191.000000  
75%        1.400000       93.994000     -36.400000      4.961000   5228.100000  
max        1.400000       94.767000     -26.900000      5.045000   5228.100000

In [7]:
a.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

# 2..Encode the predictors to convert them to numerical data.

In [8]:
x=a.drop(columns=['duration','y'])
x

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  campaign  pdays  previous     poutcome  \
0      telephone   may         mon         1    999         0  nonexistent   
1      telephone   may         mon         1    999         0  nonexistent   
2      telephone   may         mon         1    999         0  nonexistent   
3      telephone   may         mon         1    999         0  nonexistent   
4      telephone   may         mon         1    999         0  nonexistent   
...          ...   ...         ...       ...    ...       ...          ...   
41183   cellular   nov         fri         1    999         0  nonexistent   
41184   cellular   nov         fri         1    999         0  nonexistent   
41185   cellular   nov         fri         2    999         0  nonexistent   
41186   cellular   nov         fri         1    999         0  nonexistent   
41187   cellular   nov         fri         3    999         1      failure   

       emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed  
0               1.1          93.994          -36.4      4.857       5191.0  
1               1.1          93.994          -36.4      4.857       5191.0  
2               1.1          93.994          -36.4      4.857       5191.0  
3               1.1          93.994          -36.4      4.857       5191.0  
4               1.1          93.994          -36.4      4.857       5191.0  
...             ...             ...            ...        ...          ...  
41183          -1.1          94.767          -50.8      1.028       4963.6  
41184          -1.1          94.767          -50.8      1.028       4963.6  
41185          -1.1          94.767          -50.8      1.028       4963.6  
41186          -1.1          94.767          -50.8      1.028       4963.6  
41187          -1.1          94.767          -50.8      1.028       4963.6  

[41188 rows x 19 columns]

In [9]:
y=a.iloc[:,-1:]
y

y
0       no
1       no
2       no
3       no
4       no
...    ...
41183  yes
41184   no
41185   no
41186  yes
41187   no

[41188 rows x 1 columns]

In [10]:
x=pd.get_dummies(x,drop_first=True)
x

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0       56         1    999         0           1.1          93.994   
1       57         1    999         0           1.1          93.994   
2       37         1    999         0           1.1          93.994   
3       40         1    999         0           1.1          93.994   
4       56         1    999         0           1.1          93.994   
...    ...       ...    ...       ...           ...             ...   
41183   73         1    999         0          -1.1          94.767   
41184   46         1    999         0          -1.1          94.767   
41185   56         2    999         0          -1.1          94.767   
41186   44         1    999         0          -1.1          94.767   
41187   74         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...  month_may  \
0              -36.4      4.857       5191.0                0  ...          1   
1              -36.4      4.857       5191.0                0  ...          1   
2              -36.4      4.857       5191.0                0  ...          1   
3              -36.4      4.857       5191.0                0  ...          1   
4              -36.4      4.857       5191.0                0  ...          1   
...              ...        ...          ...              ...  ...        ...   
41183          -50.8      1.028       4963.6                0  ...          0   
41184          -50.8      1.028       4963.6                1  ...          0   
41185          -50.8      1.028       4963.6                0  ...          0   
41186          -50.8      1.028       4963.6                0  ...          0   
41187          -50.8      1.028       4963.6                0  ...          0   

       month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
0              0          0          0                1                0   
1              0          0          0                1                0   
2              0          0          0                1                0   
3              0          0          0                1                0   
4              0          0          0                1                0   
...          ...        ...        ...              ...              ...   
41183          1          0          0                0                0   
41184          1          0          0                0                0   
41185          1          0          0                0                0   
41186          1          0          0                0                0   
41187          1          0          0                0                0   

       day_of_week_tue  day_of_week_wed  poutcome_nonexistent  \
0                    0                0                     1   
1                    0                0                     1   
2                    0                0                     1   
3                    0                0                     1   
4                    0                0                     1   
...                ...              ...                   ...   
41183                0                0                     1   
41184                0                0                     1   
41185                0                0                     1   
41186                0                0                     1   
41187                0                0                     0   

       poutcome_success  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
41183                 0  
41184                 0  
41185                 0  
41186                 0  
41187                 0  

[41188 rows x 52 columns]

# 3..Split the data into train and test with a ratio of 80:20.

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=20,random_state=0)

In [13]:
xtrain

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
23586   49         2    999         0           1.4          93.444   
24445   42         1    999         1          -0.1          93.200   
32091   25         6    999         1          -1.8          92.893   
11813   33         3    999         0           1.4          94.465   
41134   25         1    999         0          -1.1          94.767   
...    ...       ...    ...       ...           ...             ...   
20757   52         2    999         0           1.4          93.444   
32103   56         1    999         0          -1.8          92.893   
30403   29         3    999         0          -1.8          93.075   
21243   35         1    999         0           1.4          93.444   
2732    52         1    999         0           1.1          93.994   

       cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...  month_may  \
23586          -36.1      4.962       5228.1                0  ...          0   
24445          -42.0      4.191       5195.8                0  ...          0   
32091          -46.2      1.313       5099.1                0  ...          1   
11813          -41.8      4.959       5228.1                0  ...          0   
41134          -50.8      1.041       4963.6                0  ...          0   
...              ...        ...          ...              ...  ...        ...   
20757          -36.1      4.965       5228.1                0  ...          0   
32103          -46.2      1.313       5099.1                0  ...          1   
30403          -47.1      1.365       5099.1                0  ...          0   
21243          -36.1      4.963       5228.1                0  ...          0   
2732           -36.4      4.859       5191.0                0  ...          1   

       month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
23586          0          0          0                0                1   
24445          1          0          0                1                0   
32091          0          0          0                0                0   
11813          0          0          0                0                0   
41134          1          0          0                0                1   
...          ...        ...        ...              ...              ...   
20757          0          0          0                0                0   
32103          0          0          0                0                0   
30403          0          0          0                0                1   
21243          0          0          0                1                0   
2732           0          0          0                0                0   

       day_of_week_tue  day_of_week_wed  poutcome_nonexistent  \
23586                0                0                     1   
24445                0                0                     0   
32091                0                0                     0   
11813                0                0                     1   
41134                0                0                     1   
...                ...              ...                   ...   
20757                0                1                     1   
32103                0                0                     1   
30403                0                0                     1   
21243                0                0                     1   
2732                 0                1                     1   

       poutcome_success  
23586                 0  
24445                 0  
32091                 0  
11813                 0  
41134                 0  
...                 ...  
20757                 0  
32103                 0  
30403                 0  
21243                 0  
2732                  0  

[41168 rows x 52 columns]

In [14]:
xtest

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
15500   39         3    999         0           1.4          93.918   
29034   55         2    999         0          -1.8          93.075   
11199   39         1    999         0           1.4          94.465   
22247   56         7    999         0           1.4          93.444   
27180   49         1    999         0          -0.1          93.200   
33831   43         1    999         0          -1.8          92.893   
961     58         3    999         0           1.1          93.994   
10746   28         3    999         0           1.4          94.465   
15195   24         7    999         0           1.4          93.918   
34319   34         1    999         1          -1.8          92.893   
39660   29         1      3         3          -1.8          93.876   
39653   34         1    999         0          -1.8          93.876   
23460   33         9    999         0           1.4          93.444   
29763   21         1    999         0          -1.8          93.075   
5540    50         2    999         0           1.1          93.994   
7660    27         2    999         0           1.1          93.994   
34332   33         5    999         0          -1.8          92.893   
9736    39         3    999         0           1.4          94.465   
17686   55        16    999         0           1.4          93.918   
13738   42         3    999         0           1.4          93.918   

       cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...  month_may  \
15500          -42.7      4.957       5228.1                1  ...          0   
29034          -47.1      1.405       5099.1                1  ...          0   
11199          -41.8      4.961       5228.1                1  ...          0   
22247          -36.1      4.963       5228.1                0  ...          0   
27180          -42.0      4.021       5195.8                1  ...          0   
33831          -46.2      1.281       5099.1                1  ...          1   
961            -36.4      4.856       5191.0                0  ...          1   
10746          -41.8      4.961       5228.1                0  ...          0   
15195          -42.7      4.958       5228.1                0  ...          0   
34319          -46.2      1.266       5099.1                0  ...          1   
39660          -40.0      0.683       5008.7                0  ...          1   
39653          -40.0      0.683       5008.7                0  ...          1   
23460          -36.1      4.964       5228.1                0  ...          0   
29763          -47.1      1.405       5099.1                0  ...          0   
5540           -36.4      4.857       5191.0                0  ...          1   
7660           -36.4      4.864       5191.0                0  ...          1   
34332          -46.2      1.266       5099.1                1  ...          1   
9736           -41.8      4.961       5228.1                0  ...          0   
17686          -42.7      4.961       5228.1                0  ...          0   
13738          -42.7      4.963       5228.1                1  ...          0   

       month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
15500          0          0          0                0                0   
29034          0          0          0                0                0   
11199          0          0          0                0                1   
22247          0          0          0                0                1   
27180          1          0          0                0                0   
33831          0          0          0                0                0   
961            0          0          0                0                0   
10746          0          0          0                0                0   
15195          0          0          0                0                1   
34319          0          0          0               

In [15]:
ytrain

y
23586   no
24445   no
32091   no
11813   no
41134  yes
...    ...
20757   no
32103   no
30403  yes
21243   no
2732    no

[41168 rows x 1 columns]

In [16]:
ytest

y
15500  yes
29034   no
11199   no
22247   no
27180   no
33831   no
961     no
10746   no
15195  yes
34319   no
39660  yes
39653   no
23460   no
29763   no
5540    no
7660    no
34332   no
9736    no
17686   no
13738   no

# 4..Split the data into train and test with a ratio of 80:20.

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
new=DecisionTreeClassifier()

In [19]:
new.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [20]:
pred=new.predict(xtest)
pred

array(['no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'yes', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no'],
      dtype=object)

In [21]:
ytest

y
15500  yes
29034   no
11199   no
22247   no
27180   no
33831   no
961     no
10746   no
15195  yes
34319   no
39660  yes
39653   no
23460   no
29763   no
5540    no
7660    no
34332   no
9736    no
17686   no
13738   no

# 5..Determine the accuracy, precision and recall for every class in the outcome.

In [22]:
from sklearn.metrics import precision_score,recall_score,accuracy_score,confusion_matrix

In [23]:
accuracy_score(ytest,pred)

0.7

In [24]:
precision_score(ytest,pred,average="micro")

0.7

In [25]:
confusion_matrix(ytest,pred)

array([[13,  4],
       [ 2,  1]], dtype=int64)

In [26]:
recall_score(ytest,pred,average="micro")

0.7

# 6.. Modify the hyperparameters, and build a new model. Compare the performance of both models.

In [27]:
new=DecisionTreeClassifier( 
    criterion='entropy',
    splitter='random',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    class_weight=None,
    ccp_alpha=0.0,
)

In [28]:
new.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', splitter='random')

In [29]:
pred=new.predict(xtest)
pred

array(['no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no',
       'yes', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no'],
      dtype=object)

In [30]:
ytest

y
15500  yes
29034   no
11199   no
22247   no
27180   no
33831   no
961     no
10746   no
15195  yes
34319   no
39660  yes
39653   no
23460   no
29763   no
5540    no
7660    no
34332   no
9736    no
17686   no
13738   no

In [31]:
from sklearn.metrics import precision_score,recall_score,accuracy_score,confusion_matrix

In [32]:
accuracy_score(ytest,pred)

0.75

In [33]:
precision_score(ytest,pred,average="micro")

0.75

In [34]:
confusion_matrix(ytest,pred)

array([[14,  3],
       [ 2,  1]], dtype=int64)

In [35]:
recall_score(ytest,pred,average="micro")

0.75

# EXERCISE:-1  LOGISTIC_REGRESSION

# Perform the following activities using Bank Marketing dataset.

# 1.. Consider duration, age, and campaign columns as predictors and the column “y”(states whether the client will subscribe a term deposit or not) as target  variable

In [36]:
import pandas as pd
a=pd.read_csv("bankadditionalfull1603958996760.zip")
a

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [37]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [38]:
a.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [39]:
x=a.loc[:,['duration','age','campaign']]
x

duration  age  campaign
0           261   56         1
1           149   57         1
2           226   37         1
3           151   40         1
4           307   56         1
...         ...  ...       ...
41183       334   73         1
41184       383   46         1
41185       189   56         2
41186       442   44         1
41187       239   74         3

[41188 rows x 3 columns]

In [40]:
y=a[['y']]
y

y
0       no
1       no
2       no
3       no
4       no
...    ...
41183  yes
41184   no
41185   no
41186  yes
41187   no

[41188 rows x 1 columns]

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
new=LabelEncoder()

In [43]:
new.fit(y)

C:\Users\CS-L1-PC02\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [44]:
y=new.transform(y)
y

C:\Users\CS-L1-PC02\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 0, 1, 0])

# 2.. Use 70% of the data as training data set and 30% of data as testing data set.

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [47]:
x_train

duration  age  campaign
31880       195   37         1
38177       214   54         1
2459        813   49         2
756          51   30         3
11275       359   23         1
...         ...  ...       ...
20757       559   52         2
32103       166   56         1
30403       427   29         3
21243       111   35         1
2732        132   52         1

[28831 rows x 3 columns]

In [48]:
x_test

duration  age  campaign
15500       635   39         3
29034       248   55         2
11199       207   39         1
22247       176   56         7
27180       271   49         1
...         ...  ...       ...
20920        38   35         1
15744       617   39         2
34965        68   43         1
4644        174   39         1
20742       871   46         2

[12357 rows x 3 columns]

In [49]:
y_train

array([0, 0, 0, ..., 1, 0, 0])

In [50]:
y_test

array([1, 0, 0, ..., 0, 0, 1])

In [51]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x_train=st.fit_transform(x_train)
x_test=st.transform(x_test)

# 3.. Build a logistic regression model.  

In [52]:
from sklearn.linear_model import LogisticRegression

In [53]:
lr=LogisticRegression()
    

In [54]:
lr.fit(x_train,y_train)

LogisticRegression()

In [55]:
pred=lr.predict(x_test)

In [56]:
pred

array([0, 0, 0, ..., 0, 0, 0])

In [57]:
y_test

array([1, 0, 0, ..., 0, 0, 1])

# 4.. Determine the classification accuracy rate of the model on both train and test set.

In [58]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [59]:
confusion_matrix(y_test,pred)

array([[10814,   155],
       [ 1158,   230]], dtype=int64)

In [60]:
accuracy_score(y_test,pred)

0.8937444363518653

# EXERCISE:-2 

# Perform the following activities using banknote authentication dataset.

# 1..Consider 'variance', 'skewness', 'curtosis', 'entropy' columns as predictors and the column 'class' as the target  variable

In [61]:
import pandas as pd

In [62]:
ab=pd.read_csv("databanknoteauthentication1603957797786.zip")
ab

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [64]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [65]:
ab.describe()

variance     skewness     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [68]:
ab.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [69]:
x=ab.iloc[:,0:4]
x

variance  skewness  curtosis  entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

In [70]:
y=ab[['class']]
y

class
0         0
1         0
2         0
3         0
4         0
...     ...
1367      1
1368      1
1369      1
1370      1
1371      1

[1372 rows x 1 columns]

In [75]:
from sklearn.model_selection import train_test_split

In [78]:
xi_train,xi_test,yi_train,yi_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [79]:
xi_train

variance   skewness  curtosis   entropy
122   -1.45720   9.121400  1.742500 -5.124100
1356  -4.07860   2.923900  0.870260 -0.653890
1015  -0.90784  -7.902600  6.780700  0.341790
1163   0.68180   4.850400 -5.213300 -6.104300
1034   0.67886   4.119900 -4.569000 -4.141400
...        ...        ...       ...       ...
763    0.39012  -0.142790 -0.031994  0.350840
835   -0.94255   0.039307 -0.241920  0.315930
1216   0.60050   0.999450 -2.212600  0.097399
559    2.01650  -0.252460  5.170700  1.076300
684   -2.07590  10.822300  2.643900 -4.837000

[960 rows x 4 columns]

In [80]:
xi_test

variance   skewness  curtosis  entropy
1023  -1.77130 -10.766500  10.21840 -1.00430
642    5.13210  -0.031048   0.32616  1.11510
1196  -2.01490   3.687400  -1.93850 -3.89180
31     1.48840   3.627400   3.30800  0.48921
253    5.28680   3.257000  -1.37210  1.16680
...        ...        ...       ...      ...
986    0.84546   3.482600  -3.63070 -1.39610
271    5.39150   9.994600  -3.80810 -3.36420
1266  -1.43770  -1.432000   2.11440  0.42067
769   -0.89409   3.199100  -1.82190 -2.94520
634    6.82480   5.218700  -2.54250  0.54610

[412 rows x 4 columns]

In [81]:
yi_train

class
122       0
1356      1
1015      1
1163      1
1034      1
...     ...
763       1
835       1
1216      1
559       0
684       0

[960 rows x 1 columns]

In [82]:
yi_test

class
1023      1
642       0
1196      1
31        0
253       0
...     ...
986       1
271       0
1266      1
769       1
634       0

[412 rows x 1 columns]

In [84]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
xi_train=st.fit_transform(xi_train)
xi_test=st.transform(xi_test)

# 2.. Build a logistic regression model. 

In [85]:
from sklearn.linear_model import LogisticRegression

In [86]:
new1=LogisticRegression()

In [88]:
new1.fit(xi_train,yi_train)

C:\Users\CS-L1-PC02\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [89]:
pred=new1.predict(xi_test)
pred

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,

In [90]:
yi_test

class
1023      1
642       0
1196      1
31        0
253       0
...     ...
986       1
271       0
1266      1
769       1
634       0

[412 rows x 1 columns]

# 3..Calculate the classification accuracy, precision and recall for the model

In [91]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [92]:
confusion_matrix(yi_test,pred)

array([[225,   7],
       [  0, 180]], dtype=int64)

In [93]:
accuracy_score(yi_test,pred)

0.9830097087378641